/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazPackage;
    
import DomainList.ListaDoble;
import MainPackage.MainInterfaz;
import javax.swing.JOptionPane;

/**
 *
 * @author braul
 */
public class BusquedaAvanzadaGUI extends javax.swing.JFrame {
    private String option = "0";
    private boolean check = false;
    private MainInterfaz main;
    /**
     * Creates new form BusquedaAvanzadaGUI
     */
    public BusquedaAvanzadaGUI(MainInterfaz principal) {
        initComponents();
        setLocationRelativeTo(null);
        main = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        botonIgual = new javax.swing.JRadioButton();
        botonMayor = new javax.swing.JRadioButton();
        botonMenor = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkSi = new javax.swing.JCheckBox();
        botonBuscar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel1.setText("Inserte el promedio a buscar");

        buttonGroup1.add(botonIgual);
        botonIgual.setText("Igual a");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonMayor);
        botonMayor.setText("Mayor que");
        botonMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMayorActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonMenor);
        botonMenor.setText("Menor que");
        botonMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenorActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        jLabel2.setText("número");

        jLabel3.setText("¿Quiere buscar de una profesión en específico?");

        checkSi.setText("Si");
        checkSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSiActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(botonBuscar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(checkSi))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonIgual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMayor)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(checkSi)
                .addGap(12, 12, 12)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSiActionPerformed
        if(checkSi.isSelected()){
            jTextField2.setText("");
            jTextField2.setEditable(true);
            check = true;
        }else{
            jTextField2.setText("");
            jTextField2.setEditable(false);
            check = false;
        }
    }//GEN-LAST:event_checkSiActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        option = "1";
        jTextField1.setEditable(true);// TODO add your handling code here:
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMayorActionPerformed
        option = "2";
        jTextField1.setEditable(true);// TODO add your handling code here:
    }//GEN-LAST:event_botonMayorActionPerformed

    private void botonMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenorActionPerformed
        option = "3";
        jTextField1.setEditable(true);// TODO add your handling code here:
    }//GEN-LAST:event_botonMenorActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

      
           try{
               int numero = Integer.parseInt(jTextField1.getText());
               if(numero<0 || numero>100){
                JOptionPane.showMessageDialog(null,"Inserte un número con un rango 0-100");
                option = "0";
               }

           }catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null,"Por favor, inserte un número");
               option = "0";
               
           }
        
        switch (option){
            case "1":
                if(check==true){
                    ListaDoble igualProfesion = main.buscarPromedioProfesion(Integer.parseInt(jTextField1.getText()), jTextField2.getText());
                    main.insertarJlist(main.getJList(), igualProfesion);
                    this.dispose();
                }else{
                    ListaDoble igual = main.buscarPromedio(Integer.parseInt(jTextField1.getText()));
                    main.insertarJlist(main.getJList(), igual);
                    this.dispose();
                }
                break;
            case"2":
                if(check==true){
                    ListaDoble mayorProfesion = main.buscarPromedioRangoProfesion(Integer.parseInt(jTextField1.getText()), 100, jTextField2.getText());
                    main.insertarJlist(main.getJList(), mayorProfesion);
                    this.dispose();
                }else{
                    ListaDoble mayor = main.buscarPromedioRango(Integer.parseInt(jTextField1.getText()), 100);
                    main.insertarJlist(main.getJList(), mayor);
                    this.dispose();
                }
                break;
            case"3":
                if(check==true){
                    ListaDoble menorProfesion = main.buscarPromedioRangoProfesion(0, Integer.parseInt(jTextField1.getText()), jTextField2.getText());
                    main.insertarJlist(main.getJList(), menorProfesion);
                    this.dispose();
                }else{
                    ListaDoble menor = main.buscarPromedioRango(0, Integer.parseInt(jTextField1.getText()));
                    main.insertarJlist(main.getJList(), menor);
                    this.dispose();
                }
                break;
            case "0":
                break;

        }

// TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaAvanzadaGUI(new MainInterfaz()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JRadioButton botonIgual;
    private javax.swing.JRadioButton botonMayor;
    private javax.swing.JRadioButton botonMenor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkSi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
