/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazPackage;

import DomainList.ListaDoble;
import MainPackage.MainInterfaz;
import javax.swing.JOptionPane;

/**
 *
 * @author braul
 */
public class ListadoGUI extends javax.swing.JFrame {
    private String option;
    private MainInterfaz main;
    /**
     * Creates new form ListarGUI
     */
    public ListadoGUI(MainInterfaz principal) {
        initComponents();
        setLocationRelativeTo(null);
        main = principal;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        botonNombres = new javax.swing.JRadioButton();
        botonProfesiones = new javax.swing.JRadioButton();
        botonPromedios = new javax.swing.JRadioButton();
        botonListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel1.setText("¿Basado en qué se realizará el listado?");

        buttonGroup1.add(botonNombres);
        botonNombres.setText("Nombres");
        botonNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNombresActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonProfesiones);
        botonProfesiones.setText("Profesiones");
        botonProfesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfesionesActionPerformed(evt);
            }
        });

        buttonGroup1.add(botonPromedios);
        botonPromedios.setText("Promedios");
        botonPromedios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPromediosActionPerformed(evt);
            }
        });

        botonListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonListar.setText("Listar");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonPromedios, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonProfesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(botonListar)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonProfesiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonPromedios)
                .addGap(27, 27, 27)
                .addComponent(botonListar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        switch (option){
            case "1":
                ListaDoble nombres = main.listarNombres();
                main.insertarJlist(main.getJList(), nombres);
                this.dispose();
                break;
            case"2":
                ListaDoble profesiones = main.listarProfesiones();
                main.insertarJlist(main.getJList(), profesiones);
                this.dispose();
                break;
            case"3":
                ListaDoble promedios = main.listarPromedios();
                main.insertarJlist(main.getJList(), promedios);
                this.dispose();
                break;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_botonListarActionPerformed

    private void botonNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNombresActionPerformed
        option="1";// TODO add your handling code here:
    }//GEN-LAST:event_botonNombresActionPerformed

    private void botonProfesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfesionesActionPerformed
        option="2";// TODO add your handling code here:
    }//GEN-LAST:event_botonProfesionesActionPerformed

    private void botonPromediosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPromediosActionPerformed
        option="3";// TODO add your handling code here:
    }//GEN-LAST:event_botonPromediosActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoGUI(new MainInterfaz()).setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonListar;
    private javax.swing.JRadioButton botonNombres;
    private javax.swing.JRadioButton botonProfesiones;
    private javax.swing.JRadioButton botonPromedios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
